Desafio3
AquilesAguiar/onboarding_environment pull request #3
Opened 2021-12-21 16:36 UTC by AquilesAguiar

2021-12-22 02:01 UTC, ArthurFreitas requested changes

2021-12-22 02:01 UTC, ArthurFreitas commented on phoenix/app/cad_products_phoenix/mix.exs
> +      {:castore, ">= 0.0.0"},
Essa lib está sendo usada?

2021-12-22 02:01 UTC, ArthurFreitas commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix/cache.ex
> +  def get_product(key), do: Redix.command(@conn, ["GET", key]) |> decode
O style guide recomenda evitar usar o pipe (|>) apenas uma vez. https://github.com/christopheradams/elixir_style_guide#avoid-single-pipelines

2021-12-22 02:01 UTC, ArthurFreitas commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix/cache.ex
> +  def set_product(key, value), do: Redix.command(@conn, ["SET", key, value |> :erlang.term_to_binary |> Base.encode16()])
Usar parenteses mesmo em funções unáris no pipe. https://github.com/christopheradams/elixir_style_guide#parentheses-pipe-operator

2021-12-22 02:01 UTC, ArthurFreitas commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix/cache.ex
> +    {:ok, bin} = val |> Base.decode16()
Ta difícil a leitura desse metodo, recomendo substituir por variáveis auxiliares ou a estrutura do with. https://elixirschool.com/en/lessons/basics/control_structures#with-3

2021-12-22 02:01 UTC, ArthurFreitas commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix/cache.ex
> +  def set_product(key, value), do: Redix.command(@conn, ["SET", key, value |> :erlang.term_to_binary |> Base.encode16()])
No lugar de manter tudo em uma só linha, extrai um método privado que só codifique o produto. Vai facilitar muito a leitura.

2021-12-22 02:01 UTC, ArthurFreitas commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix/cache.ex
> +  defp decode({:ok, nil}), do: {:not_found, "key not found"}
Nesses casos é mais idiomático usar a tupla {:error, razão}

2021-12-22 02:01 UTC, ArthurFreitas commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix/cache.ex
> +  def set_product(key, value), do: Redix.command(@conn, ["SET", key, value |> :erlang.term_to_binary |> Base.encode16()])
Feito tu fez com o decode

2021-12-22 02:01 UTC, ArthurFreitas commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix/cache.ex
> +  def set_product(key, value), do: Redix.command(@conn, ["SET", key, value |> :erlang.term_to_binary |> Base.encode16()])
Pode tirar o sufixo de product dos metodos nesse módulo, ele ta bem genérico e pode aceitar qualquer tipo.

2021-12-22 02:01 UTC, ArthurFreitas commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/controllers/register_controller.ex
> +  defp format_json(products) do
Essa função ta com um mal nome porque não formata json e sim indexa produtos no elastic search.

2021-12-22 02:01 UTC, ArthurFreitas commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/controllers/register_controller.ex
> +    Enum.each(products_json, fn(product) -> put("/cad_products/products/#{product.id}", product) end)
Um dos nossos usos para o elastic search é desse jeito (indexar produtos para permitir queries de forma rápida sem afetar o DB). Outra forma que utilizamos é para logar eventos para permitir auditoria depois, Ex.: Requests para a API (path, body, http verb, etc), Logs de um job rodando em background, etc.

2021-12-22 02:01 UTC, ArthurFreitas commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/controllers/register_controller.ex
> +  defp format_json(products) do
Seria legal extrair esse processo para outro modulo "ProductIndex" que isolasse essa comunicação com o ELS, da mesma forma que tu fez com o cad_products_phoenix/cache.ex

2021-12-22 02:01 UTC, ArthurFreitas commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/controllers/register_controller.ex
>  defmodule CadProductsPhoenixWeb.RegisterController do
É bom tratar para que tua aplicação resista a falhas, tanto do redis quanto do elastic search. Tenta rodar ela sem esses serviços rodando e cuida para que ela não quebre nesse caso.

2021-12-22 02:09 UTC, ArthurFreitas commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/controllers/register_controller.ex
> +    Enum.each(products_json, fn(product) -> put("/cad_products/products/#{product.id}", product) end)
Porém da forma que ta sendo feita no projeto, esse indice só é atualizado se algum usuário bater no /products. Se tu quiser seguir na proposta de indexar produtos seria legal atualizar o ELS quando o produto é criado/deletado/atualizado.

2021-12-22 18:36 UTC, gabrielzuqueto commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/controllers/register_controller.ex
> +    case Cache.get_product("products") do
A controller não deve ter lógica. Precisa mover isso para um service.

Outro ponto que é o ideal é usar sempre {:error, "string"} ou {:error, :simbolo}.

Você poderia usar {:error, :not_found}

Vou criar um esboço de service e coloco aqui como exemplo.

2021-12-22 18:36 UTC, gabrielzuqueto commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/controllers/register_controller.ex
> +        format_json(products)
O retorno do format_json não está sendo utilizado. Vou removê-lo no exemplo

2021-12-22 18:36 UTC, gabrielzuqueto commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/controllers/register_controller.ex
> +    case Cache.get_product("products") do
### Exemplo

Criei phoenix/app/cad_products_phoenix/lib/cad_products_phoenix/services/products.ex

```
defmodule CadProductsPhoenix.Services.Products do
  alias CadProductsPhoenix.Cache
  alias CadProductsPhoenix.Management

  def fetch_all do
    case Cache.get_product("products") do
      {:ok, _} = result ->
        result

      _ ->
        register = Management.list_register()
        Cache.set_product("products", register)
        {:ok, register}

    end
  end

  def create(%{"product" => product}) when is_map(product) do
    Cache.delete_product("products")
    Management.create_register(product)
  end

  def create(_params), do: {:error, 422}

  ...
end
```

Daí na controller ficou assim:

```
...
alias CadProductsPhoenix.Services.Products
...
  def index(conn, _params) do
    with {:ok, products} <- Products.fetch_all() do
      render(conn, "index.json", register: products)
    end
  end

  def create(_conn, %{"product" => register_params} ) do
    Products.create(params)
  end
```

Em index em caso de erro cai para o FallbackController. Acredito que no create, você colocou 100% no fallback controller (erro e sucesso).

No service retornei {:error, 422} caso não venha o que esperamos, daí no fallback controller, você pode fazer um pattern matching com essa estrutura e daí retorna um 422 padrão.

Isso pode ser reutilizado em toda a aplicação. Assim padroniza o retorno de erro na API.

A controller deve só fazer a ligação com a view. Não deve fazer nada além disso.

2021-12-22 18:36 UTC, gabrielzuqueto commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/controllers/register_controller.ex
> +  defp format_json(products) do
Ela nem reveria existir na controller. Deveria ficar dentro d eum service.

2021-12-23 15:21 UTC, gabrielzuqueto commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/services/product.ex
> +        result
Precisa por um default, caso contrário, se retornar erro, vai estourar por falta de match.

```
case ..
  {:ok, ...} ->
    ...

  error ->
     error
end
```

2021-12-23 15:21 UTC, gabrielzuqueto commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/services/product.ex
> +        {:ok, product}
Mesma coisa aqui, precisa por o default, para evitar erro de match

2021-12-23 15:21 UTC, gabrielzuqueto commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/services/product.ex
> +  def update(products, %{"product" => register_params} ) do
Como é um item só, ideal é chamar de product. E para ficar mais semântico, no  `{:ok, ...}`, pode por `{:ok, updated_product}`

Ou melhor, no `{:ok, ...}`, como vai retornar esse msm resultado, pode fazer assim:

```
 {:ok, _} = result ->
   Cache.delete("products")
   ProductIndex.index_products()
   result
```

2021-12-23 15:21 UTC, gabrielzuqueto commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/services/product.ex
> +  def delete(products) do
Mesmo esquema aqui. Como é um produto só, ideal é alterar para `product`.

2021-12-23 15:21 UTC, gabrielzuqueto commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/controllers/register_controller.ex
>    alias CadProductsPhoenix.Management
Esqueceu de remover os alias que não utiliza mais.

2021-12-23 15:21 UTC, gabrielzuqueto commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/controllers/fallback_controller.ex
> +  def call(conn, {:error, 422}) do
Está correto, porém, como vai exibir sempre o código do erro, pode deixar mais genérico. Mas está correto da forma que fez. É só um exemplo a mais.

```
  def call(conn, {:error, error_code}) when is_number(error_code) do
    conn
    |> put_status(error_code)
    |> put_view(CadProductsPhoenixWeb.ErrorView)
    |> render("#{error_code}")
  end
```

Ah... em um projeto real, o ideal é descrever melhor  o erro. Para isso poderia fazer algo como:

```
  def call(conn, {:error, {code: error_code, message: message}}) when is_number(error_code) do
    conn
    |> put_status(error_code)
    |> put_view(CadProductsPhoenixWeb.ErrorView)
    |> render(message)
  end
  ```
Daí pode manipular os erros para retornarem assim:

```
{:error, {code: 422, message: "Mensagem que ajude o cliente a corrigir o erro"}}
```

Como falei, é só mais um exemplo msm.

2021-12-23 15:21 UTC, gabrielzuqueto commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/controllers/fallback_controller.ex
> +    |> render(:"422")
Não precisa criar um symbol, poderia por direto `render(422)`.

2021-12-24 12:30 UTC, ArthurFreitas commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/controllers/fallback_controller.ex
> +    |>  send_resp(error_code, message)
Sobrou espaço

2021-12-24 12:30 UTC, ArthurFreitas commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/controllers/fallback_controller.ex
> +  # def call(conn, {:error, 422}) do
Sempre remova código comentado

2021-12-24 12:38 UTC, ArthurFreitas commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/controllers/register_controller.ex
> +
Sobrou espaço

2021-12-24 12:44 UTC, ArthurFreitas commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/services/product.ex
> +        ProductIndex.index_products()
Dessa forma vai pesar muito tua aplicação, sempre que o cliente acessar o index terá que buscar todos os produtos do banco e indexa-los 1 a 1 no ELS. Uma forma melhor seria: indexar o produto quando for criado/atualizado e removê-lo do indíce quando for deletado.

2021-12-24 13:56 UTC, ArthurFreitas commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix/product_index.ex
> +    IO.inspect(prod)
Sobrou o inspect

2021-12-24 13:57 UTC, ArthurFreitas commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix/product_index.ex
> +    {:ok, prod} = product
Faz esse matching na definição da função.

`def index_product({:ok, prod})`

2021-12-24 14:00 UTC, ArthurFreitas commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/services/product.ex
> +      {:ok, _} ->
Faltou pegar o produto atualizado aqui não? Tu ta repassando o product velho para o resto da função.

2021-12-24 15:28 UTC, ArthurFreitas commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix/product_index.ex
> +       %{
É bom ter um dado temporal:

`last_update_at: DateTime.to_iso8601(DateTime.utc_now())`

2021-12-24 15:28 UTC, ArthurFreitas approved these changes

2021-12-24 15:35 UTC, merged