Refactoring desafio3
AquilesAguiar/onboarding_environment pull request #4
Opened 2021-12-30 18:57 UTC by AquilesAguiar

2021-12-31 12:29 UTC, phrodrigues commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/services/product.ex
> +        Cache.delete(id)
Não precisa deletar o cache se for seta-lo denovo

2021-12-31 12:29 UTC, phrodrigues commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/services/product.ex
> +    {:ok, product} = get_cache(id)
Da pra jogar o get_cache num plugin

2022-01-04 15:12 UTC, phrodrigues commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix/product_index.ex
> +  end
Pula linha

2022-01-04 15:12 UTC, phrodrigues commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix/product_index.ex
> +    format_json_products(get("/cad_products/products/_search"))
Nesse caso seria melhor usar o operador |>

2022-01-04 15:12 UTC, phrodrigues commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix/product_index.ex
> +    format_json_products(get("cad_products/products/_search?q=#{query}"))
operador |> seria uma boa aqui

2022-01-04 15:12 UTC, phrodrigues commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix/product_index.ex
> +    query = Enum.map(params, fn {k, v} -> join_string(control, "#{k}:#{v}*&") end)
Qual o objetivo de concatenar com string vazia?

2022-01-04 15:12 UTC, phrodrigues commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix/product_index.ex
> +    products = Enum.map(products, fn(product) -> product._source end)
https://elixir-lang.org/crash-course.html#partials-and-function-captures-in-elixir

2022-01-04 15:12 UTC, phrodrigues commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/services/product.ex
> +      {:error, _mensage} -> {:ok, ProductIndex.get_all_product()}
Se a busca pelo els não der certo vai resgatar todos os produtos, como um cliente saberá se a busca dele não trouxe resultado nenhum ou encontrou muitos itens?

2022-01-04 15:12 UTC, phrodrigues commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/services/product.ex
> +      {:error, %{code: 422, message: "Unable to search, missing params"}}
A mensagem está desconexa do contexto, ao meu ver um "Items not found" seria melhor

2022-01-04 17:49 UTC, phrodrigues commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix/product_index.ex
> +    get("/cad_products/products/_search")
O style guide do elixir (https://github.com/christopheradams/elixir_style_guide) aponta pra algo do tipo:

"/cad_products/products/_search"
|> get()
|> format_json_products()

2022-01-04 17:49 UTC, phrodrigues commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix/product_index.ex
> +    get("cad_products/products/_search?q=#{query}")
Mesma coisa do comentário anterior, aliás faria sentindo um método único pros 2 casos

2022-01-04 17:49 UTC, phrodrigues commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix/product_index.ex
> +    query = Enum.map(params, fn {k, v} -> "#{k}:#{v}*&" end)
Aqui pode ser um uso do operador |>

2022-01-04 19:26 UTC, NoahCamargo requested changes

2022-01-04 19:26 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix/product_index.ex
> +
Espaço a mais

2022-01-04 19:26 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix/product_index.ex
> +    query = Enum.join(query)
Tente resumir esse **map** e **join** da seguinte forma:

```
Enum.map_join(params, "&", fn {k, v} -> "#{k}:#{v}*" end)
```

2022-01-04 19:26 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix/product_index.ex
> +  end
Se a função não esta sendo utilizada, é melhor remover

2022-01-04 19:26 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix/product_index.ex
> +  def format_json_products(products) do
Essa função é somente utilizada aqui, deixe-a privada

2022-01-04 19:26 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix/product_index.ex
> +    {:ok, 200, all_products} = products
Se der erro a aplicação vai quebrar, talvez seja melhor adicionar um case aqui

2022-01-04 19:26 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/controllers/register_controller.ex
> +    case Product.fetch_all(conn) do
Como ele só precisa do params, melhor passar ele direto

2022-01-04 19:26 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/services/product.ex
> +    if conn.params === %{} do
Por padrão utilizamos "=="

2022-01-04 19:26 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/services/product.ex
>    end
No lugar desse **if**, voce poderia aproveitar mais o matching:

```
def search_products(%{}) do
  {:search_all, ""}
end

def search_products(conn) do
  ...
end
```

Mas pelo que eu vi, esse `search_all` esta sendo usada para nada

2022-01-04 19:26 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/services/product.ex
> +        {:error, %{code: 422, message:  "Products not found"}}
Como é o index, e o cara fez um filtro que não tem resultado, acho que não deveria dar erro e sim retornar a lista vazia. O que é mais comum de ver tambem

2022-01-04 19:26 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix/product_index.ex
> +  end
daria para remover essa função e modificar a `def search_products(params) do` para `def search_products(params \\ %{}) do`

2022-01-04 19:26 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/services/product.ex
Espaço extra

2022-01-04 19:26 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/services/product.ex
> +  def show(), do: {:error, %{code: 422, message: "Unable to find the product, check if you are passing the id correctly"}}
Esse match nunca ira acontecer, ja que voce sempre esta passando um parâmetro para show

2022-01-04 19:26 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/services/product.ex
> +    {:ok, product} = cache_product
Passa esse matching para a assinatura do metodo

2022-01-04 19:26 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/controllers/register_controller.ex
> +          assign(conn, :register, {:ok, register})
Achei meio estranho jogar o :ok, no assing. Acho que fica melhor receber a estrutura e mudar lá no fallback pra caso venha o objeto ele rederize o show

2022-01-04 19:26 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/controllers/register_controller.ex
>      id = conn.params["id"]
De um espaço depois dessa linha

2022-01-04 19:26 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/services/product.ex
> +        {:ok, product} = result
Remova essa linha e pegue o product pelo matching do case `{:ok, product} = result ->`

2022-01-04 19:26 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix/product_index.ex
> +  def index_product(prod) do
Sera que `create_product` ou `update_product`, não fica melhor? Ai como ela já esta no modulo de ProductIndex, não precisa ficar repetindo index toda hora, ai a chamada ficaria `ProductIndex.create_product(product)`

2022-01-05 17:13 UTC, NoahCamargo requested changes

2022-01-05 17:13 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix/product_index.ex
> +  end
Só isso já não resolveria?

```
  def search_products(params) do
    query = Enum.map_join(params, "*&", fn {k, v} -> "#{k}:#{v}" end)

    "cad_products/products/_search?q=#{query}"
    |> get()
    |> format_json_products()
  end
```

2022-01-05 17:13 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix/product_index.ex
> +
Remover espaço

2022-01-05 17:13 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix/product_index.ex
> +      _ -> {:error, %{code: 422, message:  "Products not found"}}
Aqui na verdade a gente sabe que deu um problema na requisição, mas não sabemos se os produtos não foram encontrados. Acho que ficaria melhor um 400 mesmo uma mensagem falando que não foi possível obter os produtos ou se o elastic falhar, voce retorna o que esta no banco mesmo

2022-01-05 17:13 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/services/product.ex
> +    {:ok, ProductIndex.search_products(params)}
Se der erro, agora vai retornar `{:ok, {:error, error}}`

2022-01-05 17:13 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix/product_index.ex
> +        Enum.map products, &(&1._source)
Como o padrão agora é a tupla, retorne `:ok`, tambem

2022-01-05 17:13 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/services/product.ex
> +  def show(_product), do: {:error, %{code: 422, message: "Unable to find the product, check if you are passing the id correctly"}}
Esse show nunca sera utilizado, pois ele sempre cairá no primeiro, se a ideia é saber se o produto existe, no primeiro `show`, adicione o `%Product{}` na assinatura

2022-01-05 17:13 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/services/product.ex
> +      {:ok, product} = _result ->
Nesse caso não precisa do `_result`, daria para remove-lo. No update tambem

2022-01-05 17:13 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/services/product.ex
>    def delete(_product), do: {:error, %{code: 422, message: "Unable to delete the product, check if it exists"}}
Esses espaços entre o ultimo end do modulo e a ultima função não existem

2022-01-05 17:13 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/controllers/register_controller.ex
>    end
Se o delete retornar error, é bom repassar isso. Se não o cara vai achar que apagou o produto mas ele ainda esta lá

2022-01-05 17:38 UTC, AquilesAguiar commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix/product_index.ex
> +  end
O problema é no q=, que para passagem de parametros, mesmo que eu passe vazio ele tenta fazer a pesquisa, e como não acha nada retorna uma lista vazia, por isso separei em dois.

2022-01-05 19:19 UTC, NoahCamargo requested changes

2022-01-05 19:19 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix/product_index.ex
> +  end
Tente assim 
```
  def search_products(params) do
    query = Enum.map_join(params, "*&", fn {k, v} -> "#{k}:#{v}" end)

    "cad_products/products/_search?#{if query != "", do: "q="}#{query}"
    |> get()
    |> format_json_products()
  end
```

2022-01-05 19:19 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix/product_index.ex
> +  defp format_json_products(products) do
Uma alternativa. Algo invés do case, use o match da própria função:

```
  defp format_json_products({:ok, 200, all_products}) do
    {:ok, Enum.map(all_products.hits.hits, & &1._source)}
  end

  defp format_json_products(_) do
    {:error, %{code: 400, message: "it was not possible to get the products"}}
  end
```

2022-01-05 19:19 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/services/product.ex
> +  def show(_product), do: {:error, %{code: 422, message: "Unable to find the product, check if you are passing the id correctly"}}
Agora, como no controller voce esta passando:

```
  def show(conn, _) do
    %{"product" => conn.assigns[:register]}
    |> Product.show()
  end
```
Esse matching nunca sera utilizado. Melhor voltar o controller ao normal e apagar essa função, pois atualmente ambos os show não tem feito nada. Mas eu entendi qual era a intenção e só vai funcionar se esse show for para o controller

2022-01-05 19:19 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/services/product.ex
>    def update(product, %{"product" => register_params} ) do
Ao inves de ficar sempre fazendo esse matching
```
%{"product" => register_params}

e

 {:error, %{code: 422, message: "Unable to update the product, check if it exists or if you are passing the json correctly"}}
```

Jogue essa validação para um plug no controller

2022-01-05 20:09 UTC, NoahCamargo requested changes

2022-01-05 20:09 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix/product_index.ex
Esses espaços no começo e no final do modulo não tem. O certo é tipo assim:

```
defmodule CadProductsPhoenix.ProductIndex do
  import AlgumaCoisa
  
  ....
  
  def alguma_coisa(_params) do
  end
end
```

De uma olhada no style guide

2022-01-06 15:26 UTC, NoahCamargo requested changes

2022-01-06 15:26 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/controllers/register_controller.ex
> +    Product.delete(conn.assigns[:product])
Seria `register`, né?

2022-01-06 15:43 UTC, NoahCamargo requested changes

2022-01-06 15:43 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/services/product.ex
> +    IO.inspect(product)
Veio um inspect

2022-01-06 17:04 UTC, NoahCamargo approved these changes

2022-01-06 17:27 UTC, phrodrigues commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/services/product.ex
> +    ProductIndex.search_products(params)
O index só está dependente do els, e isso pode gerar problemas caso o els caia ou algo do tipo. Seria interessante ter uma salvaguarda, retornando a listagem geral do próprio banco caso o els esteja fora.

2022-01-06 19:15 UTC, NoahCamargo requested changes

2022-01-06 19:15 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/controllers/register_controller.ex
> +    IO.inspect(Product.fetch_products(conn.params))
IO.inspect

2022-01-06 19:15 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix/product_index.ex
> +    {:mongodb, Management.list_register()}
Como aqui é o modulo que se comunica com o els, essa parte de filtrar os produtos caso o els falhe, deveria estar no phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/services/product.ex

2022-01-07 12:11 UTC, merged