Desafio4
AquilesAguiar/onboarding_environment pull request #5
Opened 2022-01-10 16:46 UTC by AquilesAguiar

2022-01-10 20:12 UTC, NoahCamargo requested changes

2022-01-10 20:12 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/controllers/register_controller.ex
> +      %{"register" => product_params} -> assign(conn, :product_params, product_params)
Na api não esta vindo apenas como product?

2022-01-10 20:12 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/services/product.ex
> +      {:error, _} -> {:index, Management.list_register()}
Se não tiver um motivo especifico para ser index, talvez fique melhor o OK

2022-01-10 20:12 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/views/register_view.ex
> +      bar_code: register.bar_code
Melhor deixar barcode, tudo juntinho

2022-01-11 12:49 UTC, AquilesAguiar commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/services/product.ex
> +      {:error, _} -> {:index, Management.list_register()}
Possui, é para diferenciar no match do fallback

2022-01-11 14:22 UTC, AquilesAguiar commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/controllers/register_controller.ex
> +      %{"register" => product_params} -> assign(conn, :product_params, product_params)
Quando realizo o teste ele vem como register, e estava dando error, não consegui mudar o retorno de como está vindo, se tiver uma dica de como seria de grande ajuda.

2022-01-11 15:36 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/controllers/register_controller.ex
> +      %{"register" => product_params} -> assign(conn, :product_params, product_params)
Da uma reparada la em `register_controller_test.exs`, o teste que é feito para contemplar essa parte do código

2022-01-11 15:38 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/services/product.ex
> +      {:error, _} -> {:index, Management.list_register()}
Como lá não tem nenhum {:ok, register} e o match é {:index, register}, acho que não vai dar problema mudar

2022-01-13 18:27 UTC, NoahCamargo requested changes

2022-01-13 18:27 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix/management/register.ex
> +
Espaço extra

2022-01-13 18:27 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix/elastik/product_index.ex
> +    query = Enum.map_join(params, "*&", fn {k, v} -> "#{k}:#{v}" end)
Faça um AND aqui. Se a pessoa passar um filtro como `name=teste&sku=123` e existir o name, mas não com esse sku, não é para retornar

2022-01-13 18:27 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/controllers/register_controller.ex
> +          Ecto.NoResultsError ->
O one esta retornando isso?

2022-01-13 18:27 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/test/cad_products_phoenix/redis_cache_test.exs
> +        end
O Redis não precisa mockar, só da um flush em um `setup`

2022-01-13 18:27 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/test/cad_products_phoenix/redis_cache_test.exs
> +
Espaço extra

2022-01-13 18:47 UTC, AquilesAguiar commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/controllers/register_controller.ex
> +          Ecto.NoResultsError ->
Sim, se ele der error retorna o Ecto.NoResultsError

2022-01-14 13:39 UTC, NoahCamargo requested changes

2022-01-14 13:39 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix/cache.ex
> +
Espaço a mais

2022-01-14 13:39 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix/elastik/product_index.ex
> +  def product_json(prod) do
Melhor deixar privado essa função

2022-01-14 13:39 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/controllers/register_controller.ex
> +          Ecto.NoResultsError ->
É pq o seu esta com o bang operator, se remover e usar só o `one(`, vai funcionar sem precisar do try

2022-01-14 13:39 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/test/cad_products_phoenix/redis_cache_test.exs
> +
Espaço extra

2022-01-14 13:39 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/test/cad_products_phoenix/redis_cache_test.exs
> +      assert Redix.command(conn, ["SET", key, value]) == {:ok, "OK"}
No caso seria o `CadProductsPhoenix.Cache` para o teste, que é o seu modulo

2022-01-18 11:24 UTC, NoahCamargo requested changes

2022-01-18 11:24 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix/elastik/product_index.ex
> +    product_json
Como aqui voce retorna o objeto direto, não precisaria da variável

2022-01-18 11:24 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix/elastik/product_index.ex
> +    query = Enum.map_join(params, "*&", fn {k, v} -> "#{k}:#{v}%20AND%20" end)
Isso "%20AND%20" ficaria no lugar do "*&"

2022-01-18 11:24 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/controllers/register_controller.ex
> +        if register != nil do
Poderia colocar apenas `if register do`, considerando que só é falso nil e false

2022-01-18 11:24 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/config/test.exs
> +config :cad_products_phoenix, :elsk_search, link: "/cad_products_test/test/"
Como já tem teste em cad_products_test, acho que ficaria melhor "/cad_products_test/products/"

2022-01-18 11:24 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix/product_index.ex
> +    product_json
Ficou uma variável aqui

2022-01-18 11:24 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/test/cad_products_phoenix/redis_cache_test.exs
> +    Cache.flush()
Adicione um espaço depois do flush

2022-01-18 11:24 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/test/cad_products_phoenix/elsk_test.exs
> +    end
É bom fazer algo parecido com o cache, limpando os registros antes de cada testes

2022-01-18 11:24 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/test/cad_products_phoenix/management_test.exs
> +      assert %Register{} = deleted_product
Que tal fazer `assert {:ok, %Register{}} = Management.delete_register(register)`

2022-01-18 11:24 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/test/cad_products_phoenix/redis_cache_test.exs
> +      assert Cache.delete(key) == {:ok, 1}
Coloque um get depois, verificando que realmente foi apagado

2022-01-18 11:24 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/test/cad_products_phoenix/redis_cache_test.exs
> +    test "delete a data in cache, if key is invalid", %{invalid_key: invalid_key} do
Seria um not delete, não?

2022-01-18 11:24 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/test/cad_products_phoenix_web/controllers/register_controller_test.exs
>      test "lists all register", %{conn: conn} do
Aqui vai ter que testar ambos os cenários, com elastic e direto no banco

2022-01-18 11:24 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/test/cad_products_phoenix_web/controllers/register_controller_test.exs
> +      assert json_response(conn, 200)["data"] == nil
nil é ruim retornar, melhor fazer com retorne [], mesmo

2022-01-18 11:24 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/test/cad_products_phoenix_web/controllers/register_controller_test.exs
> +      assert %{"id" => id} = json_response(conn, 200)["product"]
A ideia aqui seria verificar se realmente é o mesmo id que foi passado para o update

2022-01-21 18:23 UTC, phrodrigues commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix/product_index.ex
> +    link = Application.get_env(:cad_products_phoenix, :elsk_link)[:link]
Poderia criar um método só pro link do els e outro do link com index do els

2022-01-21 18:23 UTC, phrodrigues commented on phoenix/app/cad_products_phoenix/test/cad_products_phoenix/els_test.exs
> +defmodule CadProductsPhoenix.ElskTest do
Por padrão o nome do módulo de teste remete imediatamente ao nome do módulo testado, nesse caso esse módulo deveria chamar ProductIndexTest

2022-01-21 18:23 UTC, phrodrigues commented on phoenix/app/cad_products_phoenix/test/cad_products_phoenix/els_test.exs
> +defmodule CadProductsPhoenix.ElskTest do
E também o nome do módulo de teste tem que condizer com o nome do arquivo

2022-01-21 18:23 UTC, phrodrigues commented on phoenix/app/cad_products_phoenix/test/cad_products_phoenix/els_test.exs
> +  describe "elasticksearch module test" do
Nome do describe está muito genérico, por padrão agrupa-se os testes por método ou escopo que está sendo testado, no caso deveria ter um describe para o ProductIndex.create_product e outro para o ProductIndex.delete_product

2022-01-21 18:23 UTC, phrodrigues commented on phoenix/app/cad_products_phoenix/test/cad_products_phoenix/els_test.exs
> +defmodule CadProductsPhoenix.ElskTest do
O módulo de teste não cobre todo o módulo testado, por definição todos os métodos públicos do módulo devem ser testados

2022-01-21 18:23 UTC, phrodrigues commented on phoenix/app/cad_products_phoenix/test/cad_products_phoenix/redis_cache_test.exs
> +  describe "redis cache test" do
Nome de describe genérico, separe em métodos ou escopo.

2022-01-21 18:29 UTC, ArthurFreitas commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix/product_index.ex
> +  defp get_link() do
Para evitar duplicação, que tal:

`defp get_link(product_id), do: "#{get_link()}#{product_id}"`

2022-01-21 18:32 UTC, ArthurFreitas commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix/product_index.ex
> +      _ -> {:error, 422}
Aqui seria um erro 5xx do servidor não?

2022-01-21 18:42 UTC, ArthurFreitas commented on phoenix/app/cad_products_phoenix/test/cad_products_phoenix_web/controllers/register_controller_test.exs
> +        conn = get(conn, Routes.register_path(conn, :index))
formatação

2022-01-21 18:42 UTC, ArthurFreitas commented on phoenix/app/cad_products_phoenix/test/cad_products_phoenix_web/controllers/register_controller_test.exs
> +        end do
formatação

2022-01-21 18:42 UTC, ArthurFreitas commented on phoenix/app/cad_products_phoenix/test/cad_products_phoenix_web/controllers/register_controller_test.exs
> +        end do
format

2022-01-21 18:42 UTC, ArthurFreitas commented on phoenix/app/cad_products_phoenix/test/cad_products_phoenix_web/controllers/register_controller_test.exs
> +        end do
format

2022-01-21 18:44 UTC, ArthurFreitas commented on phoenix/app/cad_products_phoenix/test/cad_products_phoenix_web/controllers/register_controller_test.exs
> +        conn = delete(conn, Routes.register_path(conn, :delete, register))
Separa por espaço a ação dos asserts

2022-01-21 18:44 UTC, ArthurFreitas commented on phoenix/app/cad_products_phoenix/test/cad_products_phoenix_web/controllers/register_controller_test.exs
> +        conn = post conn, Routes.register_path(conn, :create), product: @create_attrs
Separa por espaço a ação dos asserts

2022-01-21 18:48 UTC, NoahCamargo requested changes

2022-01-21 18:48 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix/management/register.ex
> +    |> validate_length(:barcode, min: 8, max: 10)
De 8 a 13, né?

2022-01-21 18:48 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix/product_index.ex
> +  defp product_json(prod) do
Move essa função para depois das publicas

2022-01-21 18:48 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix/product_index.ex
> +      {:ok, 200, _} -> {:ok, 200}
Como não vai ter retorno a resposta, seria um 204

2022-01-21 18:48 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix/product_index.ex
> +  def get_product(id) do
Acredito que você não esteja usando essa função. Nesse caso, pode remove-la

2022-01-21 18:48 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/test/cad_products_phoenix/management_test.exs
> -      assert_raise Ecto.NoResultsError, fn -> Management.get_register(register.id) end
É interessante verificar se realmente foi excluído, mesmo

2022-01-21 18:48 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/test/cad_products_phoenix_web/controllers/register_controller_test.exs
> +        assert response(conn, 204)
O response/2 e json_response/2, não precisam estar em um assert para retornar o erro. Poderia fazer apenas:

```
conn
|> delete(Routes.register_path(conn, :delete, register))
|> response(204)
```

2022-01-21 18:50 UTC, ArthurFreitas commented on phoenix/app/cad_products_phoenix/test/cad_products_phoenix_web/controllers/register_controller_test.exs
> +        product_string = Map.new(@product_els, fn {k, v} -> {Atom.to_string(k), v} end)
Aqui não é bem uma string, fica melhor se tu extrair o `Map.new(@product_els, fn {k, v} -> {Atom.to_string(k), v} end)`
para uma função privada e chama-la nos testes.

2022-01-24 13:05 UTC, phrodrigues commented on phoenix/app/cad_products_phoenix/test/cad_products_phoenix/product_index_test.exs
> +  describe "ProductIndex.create_product test" do
Não faz sentido colocar o "test" no final do nome, já está num framework de teste. Só o nome do método está ok. E observe no arquivo "management_test" como os testes foram criados e nomeados pela ferramenta, existe uma convenção do elixir para nomeação de métodos inserindo a aridade da função. Ex: update_register/2

2022-01-24 13:06 UTC, ArthurFreitas commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/services/product.ex
>      case Management.update_register(product, register_params) do
Quando só retorna o error, tu pode trocar por um with

2022-01-24 13:11 UTC, ArthurFreitas commented on phoenix/app/cad_products_phoenix/test/cad_products_phoenix/product_index_test.exs
> +  describe "ProductIndex.create_product test" do
Não precisa da palavra test no final, nem do ProductIndex no inicio (porque ja tá no nome do arquivo).

2022-01-24 14:17 UTC, ArthurFreitas approved these changes

2022-01-24 17:14 UTC, NoahCamargo approved these changes

2022-01-24 17:35 UTC, merged