Desafio5
AquilesAguiar/onboarding_environment pull request #6
Opened 2022-02-01 18:18 UTC by AquilesAguiar

2022-02-01 19:09 UTC, phrodrigues commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/controllers/report_controller.ex
> +    case Exq.enqueue(Exq, "report", CadProductsPhoenixWeb.Jobs.CreateReportJob, [products]) do
Quando se trabalha com processamento em background uma das convenções é empilhar o job em background com o mínimo de informações possível, já que esse irá ocupar memória de cache enquanto não for processado.

2022-02-01 19:09 UTC, phrodrigues commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/services/csv_report.ex
> +  def tocsv(map) do
O usuário final precisa de alguma forma acessar o arquivo csv, como que esse arquivo lhe será fornecido?

2022-02-01 20:28 UTC, ArthurFreitas commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/controllers/report_controller.ex
> +    case Exq.enqueue(Exq, "report", CadProductsPhoenixWeb.Jobs.CreateReportJob, [products]) do
É um pouco estranho o GET enfileirar a geração do report, que tal separar essa responsabilidade para um POST?

2022-02-01 20:29 UTC, ArthurFreitas commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/controllers/report_controller.ex
> +    path = "lib/cad_products_phoenix_web/reports/report_products.csv"
Como esse valor é constante tu pode subir para ser modulo de atributo: https://elixir-lang.org/getting-started/module-attributes.html

2022-02-01 20:35 UTC, ArthurFreitas commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/services/csv_report.ex
> +    CSV.Encoding.Encoder.encode(map, headers: true)
Evite single pipes

2022-02-01 20:37 UTC, ArthurFreitas commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/services/csv_report.ex
> +  def tocsv(map) do
Essa função faz mais do que converter para csv

2022-02-01 20:39 UTC, ArthurFreitas commented on phoenix/app/cad_products_phoenix/test/cad_products_phoenix/csv_report_test.exs
> +      assert CsvReport.tocsv(@product) == :ok
Como essa função faz mais do que converter para CSV, é preciso validar o conteúdo do arquivo salvo. Para gerarmos arquivos temporários em testes utilizamos a biblioteca https://github.com/CargoSense/briefly.

2022-02-02 12:09 UTC, AquilesAguiar commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/services/csv_report.ex
> +  def tocsv(map) do
Eu envio ele via attachment, utilizando o send_download

2022-02-02 14:41 UTC, NoahCamargo requested changes

2022-02-02 14:41 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/controllers/report_controller.ex
> +      {:ok, _} -> send_download(conn, {:file, @path})
Se é assíncrono, como vai enviar o arquivo para download logo em seguida? Se o arquivo for grande, no momento desse envio o arquivo ainda estará sendo gerado

2022-02-02 14:41 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/services/csv_report.ex
> +  defp get_folder(), do: Application.get_env(:cad_products_phoenix, :csv_folder)[:folder]
Essa função aparentemente não esta sendo utilizada

2022-02-02 14:41 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/test/cad_products_phoenix/csv_report_test.exs
> +      assert CsvReport.delete_file() == :ok
delete_file não existe, né?

2022-02-02 14:41 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/test/cad_products_phoenix/csv_report_test.exs
> +      assert CsvReport.generate_report(path) == :ok
É bom verificar se o arquivo esta como voce gostaria. Daria para utilizar um fixture

2022-02-02 18:02 UTC, ArthurFreitas commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/controllers/report_controller.ex
> +      {:ok, _id} -> send_resp(conn, 200, "report created")
Acho que aqui cabe melhor 202, já que o report não foi criado e sim enfileirado para ser processado em background

2022-02-02 18:12 UTC, ArthurFreitas commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/controllers/report_controller.ex
> +      _error -> send_resp(conn, 400, "failed to created report")
A familia de erros 4xx é para problemas no request do usuário. Se o servidor entendeu o request e ocorreu um erro seria algum 5xx.

2022-02-02 18:15 UTC, ArthurFreitas commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/services/csv_report.ex
> +    |> Enum.map(fn(x) -> x end)
Não entendi o que esse map está fazendo

2022-02-02 18:16 UTC, ArthurFreitas commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/services/csv_report.ex
> +  def csv_to_map(path) do
Se essa função só é utilizada no teste tu pode mover ela para lá

2022-02-02 18:17 UTC, ArthurFreitas commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/services/csv_report.ex
> +        last_update_at: DateTime.to_iso8601(DateTime.utc_now())
DateTime.to_iso8601(DateTime.utc_now()) não faz sentido no report

2022-02-02 18:24 UTC, NoahCamargo requested changes

2022-02-02 18:24 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/services/csv_report.ex
> +    |> Enum.map(fn(x) -> x end)
Se a intenção era transformar um enumerable em uma lista, daria apra usar o Enum.to_list

2022-02-03 14:13 UTC, ArthurFreitas commented on phoenix/app/cad_products_phoenix/config/test.exs
> +config :cad_products_phoenix, :csv_folder, folder: "test/cad_products_phoenix_web/reports/"
Essa config ta sendo usada para algo?

2022-02-03 14:17 UTC, ArthurFreitas commented on phoenix/app/cad_products_phoenix/config/test.exs
>  config :cad_products_phoenix, :redis_server, index: 1
Não é obrigatório setar outra chave no final da parte de config:

`config :sentry,
  dsn: System.get_env("SENTRY_DSN"),
  json_library: Poison
  
  #para chamar
  
  Application.get_env(:sentry, :dsn)
  `

2022-02-04 14:10 UTC, NoahCamargo requested changes

2022-02-04 14:10 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix/management/register.ex
> +        Repo.one(from p in Register, where: p.id == ^id)
Se o sku for nulo, não teria motivo para fazer a query. Pois você só estaria retornando um produto qualquer

2022-02-04 14:10 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix/management/register.ex
>      |> validate_required([:name])
Coloca SKU como required tambem

2022-02-04 14:10 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix/management/register.ex
> +  def get_query(sku, id) do
Talvez um `find_by_sku`, fique melhor no nome

2022-02-04 14:10 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix_web/services/product.ex
> +        # ProductIndex.delete_all_products()
Ficou um comentário aqui

2022-02-04 14:10 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/test/cad_products_phoenix_web/controllers/register_controller_test.exs
> +    }
Esse payload esta duplicado com o @create_attrs

2022-02-04 14:10 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/test/cad_products_phoenix_web/controllers/register_controller_test.exs
> +    sku: "#{Enum.random(0..6999)}",
Tente usar um setup_all na criação dessa fixture, talvez resolva o problema do erro de duplicidade

2022-02-04 14:10 UTC, NoahCamargo commented on phoenix/app/cad_products_phoenix/lib/cad_products_phoenix/management/register.ex
> +    |> validate_unique_sku(:sku, id)
Faltou teste para essa validação, não?

2022-02-04 17:34 UTC, NoahCamargo approved these changes

2022-02-04 17:37 UTC, merged