Desafio6
AquilesAguiar/onboarding_environment pull request #7
Opened 2022-02-16 14:27 UTC by AquilesAguiar

2022-02-16 18:34 UTC, phrodrigues commented on cad_products_phoenix/lib/cad_products_phoenix_web/services/mailer_service.ex
> +defmodule CadProductsPhoenix.Services.MailerService do
Não encontrei nenhum teste escrito para essa parte do sistema

2022-02-16 19:07 UTC, NoahCamargo requested changes

2022-02-16 19:07 UTC, NoahCamargo commented on mailer_service/config/config.exs
> +end
Talvez seja melhor setar isso em test.exs

2022-02-16 19:07 UTC, NoahCamargo commented on mailer_service/lib/mailer_service_web/services/email_service.ex
> +    conn
Da uns espaços aqui

```
    body = conn.params["email_params"]
    
    SendEmail.send_create_email(body)

    conn
```

2022-02-16 19:07 UTC, NoahCamargo commented on tmp/report_products.csv
> +123456789,some description,some name,120.5,120,78845598
Joga esse arquivo no gitignore

2022-02-18 17:48 UTC, phrodrigues commented on cad_products_phoenix/lib/cad_products_phoenix_web/services/http_service.ex
> +    case HTTPoison.post("http://localhost:4444/send", "{\"email_params\": \"#{body}\"}", [
Um ponto importante na comunicação entre sistemas diferentes é garantir o sucesso da operação. E se o sistema de envio de email estiver fora do ar, a mensagem vai se perder? Seria interessante usar um serviço de cache ou de mensagerias para fazer esse meio de campo entre os sistemas e garantir o sucesso do envio do email mesmo em situações não ideais

2022-02-18 18:55 UTC, ArthurFreitas commented on cad_products_phoenix/lib/cad_products_phoenix_web/services/http_service.ex
> +    case HTTPoison.post("http://localhost:4444/send", "{\"email_params\": \"#{body}\"}", [
Extrai a url do outro serviço para o dev.exs

2022-02-18 18:56 UTC, ArthurFreitas commented on cad_products_phoenix/lib/cad_products_phoenix_web/services/mailer_service.ex
> +  @link "http://localhost:4000/report/"
Extrai para uma config

2022-02-18 18:59 UTC, ArthurFreitas commented on cad_products_phoenix/test/cad_products_phoenix/mailer_service_test.exs
> +        assert MailerService.send_body_email() == {:ok, 200}
Precisa checar se HttpService.post foi chamado com body correto

2022-02-18 19:01 UTC, ArthurFreitas commented on cad_products_phoenix/test/cad_products_phoenix_web/controllers/report_controller_test.exs
> +      conn = post(conn, Routes.report_path(conn, :create))
Checar se Exq.enqueue foi chamado com os parametros corretos

2022-02-18 19:03 UTC, ArthurFreitas commented on cad_products_phoenix/lib/cad_products_phoenix_web/services/mailer_service.ex
> +    Base.encode64(data, [])
porque tu codifica para base 64? Melhor só enviar o body como json.

2022-02-18 19:11 UTC, ArthurFreitas commented on cad_products_phoenix/lib/cad_products_phoenix_web/services/mailer_service.ex
> +    Base.encode64(data, [])
Acho que se tu enviar sem codificação nenhuma o phoenix deve decodificar assim que chegar no outro projeto

2022-02-21 16:54 UTC, NoahCamargo requested changes

2022-02-21 16:54 UTC, NoahCamargo commented on cad_products_phoenix/lib/cad_products_phoenix_web/jobs/send_email_job .ex
> +# defmodule CadProductsPhoenixWeb.Jobs.SendEmailJob do
Se esse cara não for mais usado, pode remove-lo

2022-02-21 16:54 UTC, NoahCamargo commented on mailer_service/test/mailer_service_web/controllers/email_controller_test.exs
> +  setup %{conn: conn} do
Espaço entre linha 13 e 14

2022-02-21 16:54 UTC, NoahCamargo commented on tmp/report_products.csv
> +123456789,some description,some name,120.5,120,78845598
Acho que pra esse cara sumir daqui teria que comitar removendo ele e depois adicionar o ignore

2022-02-22 14:40 UTC, NoahCamargo requested changes

2022-02-22 14:40 UTC, NoahCamargo commented on mailer_service/config/test.exs
> +if Mix.env() == :test do
Ai não vai precisar disso, pq você já esta em test

2022-02-22 16:32 UTC, NoahCamargo approved these changes

2022-02-23 11:41 UTC, phrodrigues approved these changes

2022-02-23 17:38 UTC, ArthurFreitas commented on cad_products_phoenix/lib/cad_products_phoenix_web/services/mailer_service.ex
> +    data = Poison.encode!(body, [])
pode substituir as duas linhas por apenas `Poison.encode!(body, [])`

2022-02-23 17:59 UTC, ArthurFreitas approved these changes

2022-02-23 18:16 UTC, merged